Chart.register(ChartDataLabels);
const P={shop:{ar:`الكوفي شوب`,en:`Coffee Shop`,capex:399000,land:800000,rev:437675,ebitda:22000,irrEx:24.95,irrIn:7.2,npvEx:304193,npvIn:-495807,score:69.25,dscr:1.24,loan:7,status:`ok`,sar:`موصى به بشروط`,sen:`Conditionally Recommended`,trend:{revenue:[437675,459559,482537,506664,531997,558597,586527,615853,646646,678978],ebitda:[22000,29200,37700,47000,57300,68600,81000,94600,109300,125300],fcf:[-85000,18000,24500,32000,40000,49000,59000,70000,82000,95000],net:[-8000,3500,11500,20500,30300,41200,53100,66200,80500,96100]}},school:{ar:`المدرسة الخاصة`,en:`Private School`,capex:2880000,land:800000,rev:819350,ebitda:-283138,irrEx:-4.49,irrIn:-8.6,npvEx:-1718803,npvIn:-2518803,score:40.2,dscr:-.32,loan:10,status:`no`,sar:`غير موصى به`,sen:`Not Recommended`,trend:{revenue:[819350,876705,938074,1003739,1074001,1149181,1229624,1315698,1407797,1506343],ebitda:[-283138,-251000,-216500,-179000,-138000,-94000,-46000,7000,65000,128000],fcf:[-410000,-350000,-280000,-200000,-120000,-40000,50000,140000,240000,350000],net:[-390000,-356000,-318000,-276000,-230000,-179000,-123000,-62000,5000,78000]}},house:{ar:`الكوفي هاوس`,en:`Coffee House`,capex:735000,land:800000,rev:711850,ebitda:-76115,irrEx:-6.12,irrIn:-10.1,npvEx:-445995,npvIn:-1245995,score:52.1,dscr:.18,loan:8,status:`re`,sar:`إعادة تصميم مطلوبة`,sen:`Redesign Required`,trend:{revenue:[711850,747443,784815,824056,865259,908522,953948,1001646,1051728,1104314],ebitda:[-76115,-61200,-45200,-28000,-9500,10500,32000,55100,80000,106700],fcf:[-140000,-105000,-68000,-28000,15000,62000,112000,166000,224000,286000],net:[-96000,-81000,-65000,-47000,-28000,-7000,16000,41000,68000,97000]}}};
const R=[[`التنظيم والترخيص`,`Zoning & licensing`,`critical`,`فجوة حرجة`,`Critical gap`],[`المواقف والحركة`,`Parking & circulation`,`pending`,`قيد التحقق`,`Pending`],[`الطلب والمنافسة`,`Demand & competition`,`pending`,`قيد التحقق`,`Pending`],[`عروض الإنشاء والتجهيز`,`Construction & equipment quotes`,`partial`,`تحقق جزئي`,`Partially verified`],[`التمويل البنكي`,`Bank financing`,`pending`,`قيد التحقق`,`Pending`],[`قيمة الأرض`,`Land valuation`,`partial`,`تحقق جزئي`,`Partially verified`],[`الضرائب والضمان`,`Tax & social security`,`pending`,`قيد التحقق`,`Pending`],[`الخدمات والضوضاء`,`Utilities & noise`,`pending`,`قيد التحقق`,`Pending`]];
let S={lang:localStorage.getItem(`rab_lang`)||`ar`,land:localStorage.getItem(`rab_land`)||`ex`,project:localStorage.getItem(`rab_project`)||`all`,metric:localStorage.getItem(`rab_metric`)||`revenue`,years:+(localStorage.getItem(`rab_years`)||10)};
let C={};
const nf=new Intl.NumberFormat(`en-US`,{maximumFractionDigits:0}),pf=new Intl.NumberFormat(`en-US`,{maximumFractionDigits:2});
const t=(a,e)=>S.lang===`ar`?a:e;
const m=v=>`${v<0?`−`:``}${nf.format(Math.abs(v))}`;
const save=()=>{localStorage.setItem(`rab_lang`,S.lang);localStorage.setItem(`rab_land`,S.land);localStorage.setItem(`rab_project`,S.project);localStorage.setItem(`rab_metric`,S.metric);localStorage.setItem(`rab_years`,S.years)};
const entries=()=>S.project===`all`?Object.entries(P):[[S.project,P[S.project]]];
function lang(){document.documentElement.lang=S.lang;document.documentElement.dir=S.lang===`ar`?`rtl`:`ltr`;document.body.dir=document.documentElement.dir;document.querySelectorAll(`[data-ar]`).forEach(x=>x.innerHTML=x.dataset[S.lang]);document.getElementById(`lang`).textContent=S.lang===`ar`?`English`:`العربية`;render()}
function kpis(){const p=entries().length===1?entries()[0][1]:P.shop,cap=p.capex+(S.land===`inc`?p.land:0),npv=S.land===`inc`?p.npvIn:p.npvEx,irr=S.land===`inc`?p.irrIn:p.irrEx,A=[[t(`الاستثمار الكلي`,`Total investment`),m(cap),t(`دينار أردني`,`JOD`),`warn`],[t(`إيراد السنة الأولى`,`Year 1 revenue`),m(p.rev),t(`دينار أردني`,`JOD`),`good`],[`EBITDA`,m(p.ebitda),`${t(`هامش`,`Margin`)} ${pf.format(p.ebitda/p.rev*100)}%`,p.ebitda>=0?`good`:`bad`],[`NPV`,m(npv),t(`صافي القيمة الحالية`,`Net present value`),npv>=0?`good`:`bad`],[`IRR`,`${pf.format(irr)}%`,S.land===`inc`?t(`مع الأرض`,`Including land`):t(`دون الأرض`,`Excluding land`),irr>=0?`good`:`bad`],[t(`درجة القرار`,`Decision score`),pf.format(p.score),`/ 100`,p.score>=60?`good`:p.score>=50?`warn`:`bad`],[t(`الحد الأدنى DSCR`,`Minimum DSCR`),pf.format(p.dscr),`x`,p.dscr>=1.2?`good`:`bad`],[t(`فترة القرض`,`Loan term`),p.loan,t(`سنوات`,`years`),`warn`]];document.getElementById(`kpis`).innerHTML=A.map((x,i)=>`<article class="kpi"><em>${String(i+1).padStart(2,`0`)}</em><span>${x[0]}</span><b class="num">${x[1]}</b><small class="${x[3]}">${x[2]}</small></article>`).join(``)}
function cards(){document.getElementById(`cards`).innerHTML=Object.entries(P).map(([k,p])=>{const cap=p.capex+(S.land===`inc`?p.land:0),npv=S.land===`inc`?p.npvIn:p.npvEx,irr=S.land===`inc`?p.irrIn:p.irrEx;return `<article class="project ${k===`shop`?`best`:``}"><div class="ptop"><div><p>${t(`البديل الاستثماري`,`Investment alternative`)}</p><h3>${t(p.ar,p.en)}</h3></div><div class="score" style="--s:${p.score}"><b class="num">${pf.format(p.score)}</b></div></div><div class="rows"><div class="row"><span>${t(`الاستثمار`,`Investment`)}</span><b class="num">${m(cap)}</b></div><div class="row"><span>${t(`الإيراد`,`Revenue`)}</span><b class="num">${m(p.rev)}</b></div><div class="row"><span>EBITDA</span><b class="num ${p.ebitda<0?`bad`:``}">${m(p.ebitda)}</b></div><div class="row"><span>NPV</span><b class="num ${npv<0?`bad`:``}">${m(npv)}</b></div><div class="row"><span>IRR</span><b class="num ${irr<0?`bad`:``}">${pf.format(irr)}%</b></div></div><span class="badge ${p.status}">${t(p.sar,p.sen)}</span></article>`}).join(``)}
const grid=`rgba(103,119,122,.15)`,colors=[`#099999`,`#91383d`,`#a57943`];
function kill(n){if(C[n])C[n].destroy()}
function axes(y){return{x:{title:{display:true,text:t(`المشروع / السنة`,`Project / Year`)},grid:{display:false}},y:{title:{display:true,text:y},ticks:{callback:v=>nf.format(v)},grid:{color:grid}}}}
function charts(){const E=entries();kill(`compare`);C.compare=new Chart(document.getElementById(`compareChart`),{type:`bar`,data:{labels:E.map(([,p])=>t(p.ar,p.en)),datasets:[{label:t(`الاستثمار`,`Investment`),data:E.map(([,p])=>p.capex+(S.land===`inc`?p.land:0)),backgroundColor:`#073b3a`,borderRadius:7},{label:t(`إيراد السنة الأولى`,`Year 1 revenue`),data:E.map(([,p])=>p.rev),backgroundColor:`#099999`,borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:`bottom`},datalabels:{anchor:`end`,align:`top`,font:{size:10,weight:`600`},formatter:m}},scales:axes(t(`دينار أردني`,`JOD`))}});const keys=S.project===`all`?[`shop`,`school`,`house`]:[S.project],names={revenue:t(`الإيرادات السنوية`,`Annual revenue`),ebitda:`EBITDA`,fcf:t(`التدفق النقدي الحر`,`Free cash flow`),net:t(`صافي الربح`,`Net profit`)};document.getElementById(`trendTitle`).textContent=names[S.metric];kill(`trend`);C.trend=new Chart(document.getElementById(`trendChart`),{type:`line`,data:{labels:Array.from({length:S.years},(_,i)=>`${t(`سنة`,`Year`)} ${i+1}`),datasets:keys.map((k,i)=>({label:t(P[k].ar,P[k].en),data:P[k].trend[S.metric].slice(0,S.years),borderColor:colors[i],backgroundColor:colors[i],tension:.3,borderWidth:3,pointRadius:3}))},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:`bottom`},datalabels:{display:c=>c.dataIndex===0||c.dataIndex===c.dataset.data.length-1,align:`top`,formatter:m,font:{size:9,weight:`600`}}},scales:axes(t(`دينار أردني`,`JOD`))}});kill(`npv`);const D=E.map(([,p])=>S.land===`inc`?p.npvIn:p.npvEx);C.npv=new Chart(document.getElementById(`npvChart`),{type:`bar`,data:{labels:E.map(([,p])=>t(p.ar,p.en)),datasets:[{data:D,backgroundColor:D.map(v=>v>=0?`#28705a`:`#91383d`),borderRadius:7}]},options:{indexAxis:`y`,responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},datalabels:{anchor:`end`,align:c=>c.dataset.data[c.dataIndex]>=0?`right`:`left`,formatter:m,font:{size:9,weight:`700`}}},scales:{x:{title:{display:true,text:`NPV (JOD)`},ticks:{callback:v=>nf.format(v)},grid:{color:grid}},y:{title:{display:true,text:t(`المشروع`,`Project`)},grid:{display:false}}}}})}
function risks(){document.getElementById(`risks`).innerHTML=R.map(r=>`<article class="risk"><div class="riskTop"><span class="riskTag ${r[2]}">${t(r[3],r[4])}</span><span class="num">P${r[2]===`critical`?1:r[2]===`pending`?2:3}</span></div><h4>${t(r[0],r[1])}</h4><p>${t(`يتطلب مستندات أو تحققًا مستقلًا قبل الالتزام الاستثماري.`,`Requires documents or independent verification before commitment.`)}</p></article>`).join(``)}
function scenario(){kill(`scenario`);const rg=+document.getElementById(`rg`).value/100,ci=+document.getElementById(`ci`).value/100,cf=+document.getElementById(`cf`).value/100,rev=[],eb=[];for(let i=0;i<10;i++){const r=P.shop.rev*Math.pow(1+rg,i),cost=(P.shop.rev-P.shop.ebitda)*Math.pow(1+ci,i);rev.push(r);eb.push(r-cost-(i===0?P.shop.capex*(cf-1):0))}C.scenario=new Chart(document.getElementById(`scenarioChart`),{type:`line`,data:{labels:Array.from({length:10},(_,i)=>`${t(`سنة`,`Year`)} ${i+1}`),datasets:[{label:t(`الإيرادات`,`Revenue`),data:rev,borderColor:`#099999`,backgroundColor:`#099999`,borderWidth:3,tension:.3},{label:`EBITDA`,data:eb,borderColor:`#a57943`,backgroundColor:`#a57943`,borderWidth:3,tension:.3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:`bottom`},datalabels:{display:c=>c.dataIndex===0||c.dataIndex===9,align:`top`,formatter:m,font:{size:9,weight:`600`}}},scales:axes(t(`دينار أردني`,`JOD`))}})}
function render(){kpis();cards();charts();risks();scenario()}
function sync(){project.value=S.project;metric.value=S.metric;years.value=S.years;ex.classList.toggle(`on`,S.land===`ex`);inc.classList.toggle(`on`,S.land===`inc`)}
lang.onclick=()=>{S.lang=S.lang===`ar`?`en`:`ar`;save();lang()};project.onchange=e=>{S.project=e.target.value;save();render()};metric.onchange=e=>{S.metric=e.target.value;save();charts()};years.onchange=e=>{S.years=+e.target.value;save();charts()};ex.onclick=()=>{S.land=`ex`;save();sync();render()};inc.onclick=()=>{S.land=`inc`;save();sync();render()};reset.onclick=()=>{S={...S,land:`ex`,project:`all`,metric:`revenue`,years:10};save();sync();preset(`base`);render()};
function preset(n){const q={conservative:[1,6,115],base:[5,3,100],optimistic:[8,2,95]}[n];rg.value=q[0];ci.value=q[1];cf.value=q[2];document.querySelectorAll(`[data-s]`).forEach(b=>b.classList.toggle(`on`,b.dataset.s===n));outs();scenario()}
function outs(){rgO.textContent=`${(+rg.value).toFixed(1)}%`;ciO.textContent=`${(+ci.value).toFixed(1)}%`;cfO.textContent=`${cf.value}%`}
document.querySelectorAll(`[data-s]`).forEach(b=>b.onclick=()=>preset(b.dataset.s));[rg,ci,cf].forEach(x=>x.oninput=()=>{outs();scenario()});sync();outs();lang();window.addEventListener(`load`,()=>window.setTimeout(()=>document.getElementById(`appLoader`)?.classList.add(`hide`),650));